# #Eligibility
#
# Reference for developers
#
# OpenAPI spec version: v3
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 2.4.17
#

# Common files
require_relative './swagger_client/api_client'
require_relative './swagger_client/api_error'
require_relative './swagger_client/version'
require_relative './swagger_client/configuration'

# Models
require_relative './swagger_client/models/additional_identification'
require_relative './swagger_client/models/additional_information'
require_relative './swagger_client/models/address'
require_relative './swagger_client/models/benefits_additional_information'
require_relative './swagger_client/models/benefits_date_information'
require_relative './swagger_client/models/benefits_information'
require_relative './swagger_client/models/benefits_related_entity'
require_relative './swagger_client/models/benefits_service_delivery'
require_relative './swagger_client/models/composite_medical_procedure_identifier'
require_relative './swagger_client/models/eligibility_additional_information'
require_relative './swagger_client/models/encounter'
require_relative './swagger_client/models/error'
require_relative './swagger_client/models/health_care_diagnosis_code'
require_relative './swagger_client/models/health_care_information'
require_relative './swagger_client/models/health_check'
require_relative './swagger_client/models/information_receiver_name'
require_relative './swagger_client/models/loop_2000_cd2100_cd_segment_nm1_ref_dmg_ins_mpi_prv_notes_response_member'
require_relative './swagger_client/models/loop_2100_a_segments_nm1_and_per_notes_information_source_name'
require_relative './swagger_client/models/loop_2100_a_segments_per_element_per03_8_notes_communication'
require_relative './swagger_client/models/loop_2100_a_segments_per_notes_information_source_contact_information'
require_relative './swagger_client/models/loop_2100_bcd_segment_nm1_prv_notes_provider'
require_relative './swagger_client/models/loop_2100_cd_segment_trn_notes_subscriber_trace_numbers'
require_relative './swagger_client/models/loop_2110_cd_segments_ref_notes_subscriber_dependent_additional_identification'
require_relative './swagger_client/models/medical_eligibility'
require_relative './swagger_client/models/medical_procedure'
require_relative './swagger_client/models/plan_date_information'
require_relative './swagger_client/models/plan_status'
require_relative './swagger_client/models/provider'
require_relative './swagger_client/models/provider_information'
require_relative './swagger_client/models/raw_x12_request'
require_relative './swagger_client/models/request_dependent'
require_relative './swagger_client/models/request_subscriber'
require_relative './swagger_client/models/response'

# APIs
require_relative './swagger_client/eligibility_api'

module ChangeHealthcare
  module Eligibility
    ##
    # This module contains an auto-generated client based on swagger docs.
    # Unfortunately Change Healthcare chose some *horrific* names for their
    # models, so this is more than a little gross to actuall use.
    #
    # Sorry!
    module SwaggerClient
      class << self
        # Customize default settings for the SDK using block.
        #   SwaggerClient.configure do |config|
        #     config.username = "xxx"
        #     config.password = "xxx"
        #   end
        # If no block given, return the default Configuration object.
        def configure
          if block_given?
            yield(Configuration.default)
          else
            Configuration.default
          end
        end
      end
    end
  end
end
