# #Eligibility
#
# Reference for developers
#
# OpenAPI spec version: v3
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 2.4.17
#

module ChangeHealthcare
  module Eligibility
    module SwaggerClient
      VERSION = '1.0.0'.freeze
    end
  end
end
